[project]
name = "workshop-foc-2026"
version = "0.1.0"
description = "Workshop: Future of Construction 26"
readme = "README.md"
requires-python = "~=3.14.0"
dynamic = ["dependencies"]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "rhino-stubs",
]

[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.build.targets.wheel]
packages = []

[tool.uv]
package = false

[tool.ruff]
line-length = 179

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
force-single-line = true
