[project]
name = "workshop-foc-2026"
version = "0.1.0"
description = "Workshop: Future of Construction 26"
readme = "README.md"
requires-python = "~=3.14.0"
dependencies = [
    "compas==2.15.0",
    "compas-cadwork>=0.10.0",
    "compas_timber==1.0.4",
    "cwmath>=0.0.9",
    "pythonnet",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "rhino-stubs",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 179

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
force-single-line = true
