[project]
name = "workshop-foc-2026"
version = "0.1.0"
description = "Workshop: Future of Construction 26"
readme = "README.md"
requires-python = "~=3.14.0"
dependencies = [
    "compas==2.15.1",
    "compas_timber==2.1.1-rc0",
    "timber_design==0.1.0",
    "pythonnet", 
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "rhino-stubs",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 179

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
force-single-line = true
